[package]
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
license = "MIT"
name = "paladin"
version = "0.1.0"

[dependencies]
conrod = "0.44"
docopt = "0.6"
find_folder = "0.3"
piston_window = "0.52"
rustc-serialize = "0.3"

[dependencies.pal]
git = "https://github.com/saghm/pal.git"
